### ISSUE TITLE
Add heroku deploy step to `.circleci\config.yml`.

### ISSUE THREAD

**Issue by brucestull** [brucestull/personal-assistant#224]
Add:

```yml
      # Step 4: deploy to Heroku
      - deploy:
          name: deploy to Heroku
          command: |
            heroku login -i
            heroku git:remote -a your-heroku-app-name
            git push heroku master
```

Finally:

```yml
# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.11.5
    parallelism: 3

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pipenv install
      # Step 3: run linter and tests
      - run:
          name: run linter
          command: |
            pipenv run flake8 --exclude=migrations,common.py,wsgi.py,manage.py --ignore=F403,F405 --statistics
      - run:
          name: run tests and coverage
          command: |
            pipenv run coverage run --source='.' ./manage.py test
            pipenv run coverage report
      # Step 4: deploy to Heroku
      - deploy:
          name: deploy to Heroku
          command: |
            heroku login -i
            heroku git:remote -a your-heroku-app-name
            git push heroku master
```
